# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:categories/:title/
relative_permalinks: false

# Setup
title:               Madokakaroto
tagline:             '(◉３◉)  is writing cpp'
description:         'Do the impossible, see the invisible. Raw! Raw! Fight the power! Touch the untouchable, break the unbreakable. Raw! Raw! Fight the power!!'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

plugins:            [jekyll-paginate]
mermaid:
  src:              'https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.js'